### ISSUE TITLE
HOW TO FIX THIS ERROR ?

### ISSUE THREAD

**Issue by gowri321** [pythontester192/Instagram-Bot-Scrape-DM-Users#4]
Traceback (most recent call last):
  File "C:\Users\Administrator\OneDrive\Desktop\Instagram-Bot-Scrape-DM-Users-main\scrape.py", line 145, in <module>
    scrape()
  File "C:\Users\Administrator\OneDrive\Desktop\Instagram-Bot-Scrape-DM-Users-main\scrape.py", line 49, in scrape
    user_element = WebDriverWait(bot, ELEMENTS_TIMEOUT).until(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by Exotic-duck** [comment]
change the xpath of username and the password and the Bottum

**Comment by pythontester192** [comment]
Everything Fixed Now! Try Again.
But Before that make sure to upgrade selenium to the lastet version: pip install selenium --upgrade

**Comment by gowri321** [comment]
> Everything Fixed Now! Try Again. But Before that make sure to upgrade selenium to the lastet version: pip install selenium --upgrade

OKAY !
