### ISSUE TITLE
Not logging in

### ISSUE THREAD

**Issue by zgtibu** [pythontester192/Instagram-Bot-Scrape-DM-Users#5]
File "C:\Users\91989\Downloads\Instagram-Bot-Scrape-DM-Users-main\Instagram-Bot-Scrape-DM-Users-main\scrape.py", line 145, in <module>
    scrape()
  File "C:\Users\91989\Downloads\Instagram-Bot-Scrape-DM-Users-main\Instagram-Bot-Scrape-DM-Users-main\scrape.py", line 49, in scrape
    user_element = WebDriverWait(bot, ELEMENTS_TIMEOUT).until(
  File "C:\Users\91989\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by Exotic-duck** [comment]
change the xpath of username and the password and the Bottum

**Comment by zgtibu** [comment]
Can you please explain?

**Comment by Exotic-duck** [comment]
![IMG_20221203_163857.jpg](https://user-images.githubusercontent.com/116358487/205446391-15daab6c-ae2f-4e6a-bb65-fa5b65edcd2b.jpg)
Try to change the green character like this

**Comment by zgtibu** [comment]
I chaned code  but getting this error in login page

DevTools listening on ws://127.0.0.1:51198/devtools/browser/afaae8f3-55b4-4f66-b553-272555a9d485
Logging in...
Traceback (most recent call last):
  File "C:\Users\91989\Downloads\Instagram-Bot-Scrape-DM-Users-main\Instagram-Bot-Scrape-DM-Users-main\scrape.py", line 145, in <module>
    scrape()
  File "C:\Users\91989\Downloads\Instagram-Bot-Scrape-DM-Users-main\Instagram-Bot-Scrape-DM-Users-main\scrape.py", line 49, in scrape
    user_element = WebDriverWait(bot, ELEMENTS_TIMEOUT).until(
  File "C:\Users\91989\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by keegieO** [comment]
same

**Comment by pythontester192** [comment]
Everything Fixed Now! Try Again.

**Comment by pyvcode** [comment]
ERROR: The system was unable to find the specified registry key or value.
Traceback (most recent call last):
  File "C:\Users\whata\OneDrive\Desktop\Instagram-Bot-Scrape-DM-Users-main\Instagram-Bot-Scrape-DM-Users-main\scrape.py", line 146, in <module>
    scrape()
  File "C:\Users\whata\OneDrive\Desktop\Instagram-Bot-Scrape-DM-Users-main\Instagram-Bot-Scrape-DM-Users-main\scrape.py", line 42, in scrape
    bot = webdriver.Chrome(executable_path=CM().install(), options=options)
                                           ^^^^
  File "C:\Users\whata\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\webdriver_manager\chrome.py", line 25, in __init__
    self.driver = ChromeDriver(name=name,
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\whata\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\webdriver_manager\driver.py", line 57, in __init__
    self.browser_version = chrome_version(chrome_type)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\whata\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\webdriver_manager\utils.py", line 155, in chrome_version
    raise ValueError(f'Could not get version for Chrome with this command: {cmd}')
ValueError: Could not get version for Chrome with this command: reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version

**Comment by pyvcode** [comment]
hey how would i fix this
